{% set name = "copier" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copier-{{ version }}.tar.gz
  sha256: a204c3aba22fd97ce69220ea378b924e30d516eca0e7885ab1857fde8b8dc5c5

build:
  entry_points:
    - copier = copier.cli:CopierApp.run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
    - poetry-dynamic-versioning
  run:
    - colorama >=0.4.3
    - dunamai >=1.7.0
    - funcy >=1.17
    - jinja2 >=3.1.1
    - jinja2-ansible-filters >=1.3.1
    - packaging >=23.0
    - pathspec >=0.9.0
    - plumbum >=1.6.9
    - pydantic >=1.10.2
    - pygments >=2.7.1
    - python >=3.8
    - pyyaml >=5.3.1
    - pyyaml-include >=1.2
    - questionary >=1.8.1
    - git >=2.27

test:
  imports:
    - copier
  commands:
    - pip check
    - copier --help
  requires:
    - pip

about:
  home: https://github.com/copier-org/copier
  summary: A library for rendering project templates.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kir0ul
    - fcollonval
