{% set name = "copier" %}
{% set version = "9.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/copier-{{ version }}.tar.gz
  sha256: 83b6b777b1e2e7cf13479ebfabe7ce4c02861c97bed9f533d5dce0b4822ab1d5

build:
  entry_points:
    - copier = copier.cli:CopierApp.run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry-core >=1.7.0
    - poetry-dynamic-versioning >=1.1.0
  run:
    - colorama >=0.4.6
    - dunamai >=1.7.0
    - funcy >=1.17
    - jinja2 >=3.1.4
    - jinja2-ansible-filters >=1.3.1
    - packaging >=23.0
    - pathspec >=0.9.0
    - plumbum >=1.6.9
    - pydantic >=2.4.2
    - pygments >=2.7.1
    - python >=3.8,<4.0
    - pyyaml >=5.3.1
    - questionary >=1.8.1
    - git >=2.27
    - typing-extensions >=3.7.4,<5.0.0
    - eval-type-backport >=0.1.3,<0.3.0

test:
  imports:
    - copier
  commands:
    - pip check
    - copier --help
  requires:
    - pip

about:
  home: https://github.com/copier-org/copier
  summary: A library for rendering project templates.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kir0ul
    - fcollonval
    - thewchan
