schema_version: 1

context:
  name: copier
  version: 9.10.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/copier-${{ version }}.tar.gz
  sha256: ba2d729465508da04a62bc9b76eed13d952aa7634a74a69519252fcf8a54d94e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - copier = copier.__main__:CopierApp.run

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - colorama >=0.4.6
    - dunamai >=1.7.0
    - funcy >=1.17
    - jinja2 >=3.1.5
    - jinja2-ansible-filters >=1.3.1
    - packaging >=23.0
    - pathspec >=0.9.0
    - plumbum >=1.6.9
    - prompt-toolkit <3.0.52
    - pydantic >=2.4.2
    - pygments >=2.7.1
    - pyyaml >=5.3.1
    - questionary >=1.8.1
    - eval-type-backport >=0.1.3,<0.3.0
    - platformdirs >=4.3.6
    - typing_extensions >=4.0.0,<5.0.0

tests:
  - python:
      imports:
        - copier
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - copier --help

about:
  summary: A library for rendering project templates.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/copier-org/copier

extra:
  recipe-maintainers:
    - kir0ul
    - fcollonval
    - thewchan
    - pavelzw
